os: linux
language: node_js
node_js:
  - 11.4.0
services: docker
env:
  jobs:
    - USE_SENTRY=1

before_install:
  - docker pull getsentry/sentry-cli

script:
  - yarn
  - yarn run build

before_deploy:
  - bash deploy/sentry_release.sh
  - zip -r dist.zip dist

deploy:
  provider: releases
  cleanup: false
  token:
    secure: ${GH_TOKEN}
  file: dist.zip
  on:
    repo: VirtualJudge/VirtualJudgeFE
    all_branches: true
  overwrite: true
  
