os: linux
language: node_js
node_js:
- 11.4.0
services: docker
env:
  jobs:
  - USE_SENTRY=1
before_install:
- docker pull getsentry/sentry-cli
script:
- yarn
- yarn run build
before_deploy:
- bash deploy/sentry_release.sh
- zip -r dist.zip dist
deploy:
  provider: releases
  api_key:
    secure: BlbTQOtJ0cj0IOvwmUmxKe5EGsM3bHVPJ8Mnc3EWXzsMl/kLffMiCXFerYUmozcGmTgC555ZzkBc8YCHXpKQmr3lC13p0bd2CzOch7Q8b3Ib+O9kR9zBpEzj7ThTlCD0gJifGpz9AloxbH8z9rSuKhX5D1uMf/lsS7oH8QhTAUT72zQ+YAaH4NoVBzzXQtI4yZwslzcT1HdIDMlkglyMSM3IfyHA294VskK/bxLfN/BSpdfxzmnrfFkK+W2KNWhed7ALzuFeGotEnZEgTHE3gce9HXyg3SH6gNv3wxtMqgYFDAA5VApHnTMo5Lv4khzBnsHgBOxf3xDRTmelykfFq2vGqstiQfC/3ID1Iql6iERjErYj3TamDpalvklv+9iDrUG5Tza7HNLQGxKnx6EINx9DmF7yBiO7n/wGCtsLjDA4W2IyqaZxqX+ukVM5OOSu/gIMlq6hU+BDM3zK4sErjbtQmYyJpn2IzDLhUNRfX+FCkE9PGRxA2cZXLRJW0MOA7pZD5Nju8huCzdmoN2ProtkHZxwltPv9f//PUCsyX4swFcGVBgXT4ngR0yCoBfeq1T/pTo5Gb/WTJushk6BQMSPlAYBtnK4G9gZdiR2eKrzOlB4GJ4ovcFdoBFLYIUSVSlFwWoYsedyKgBUWBiSmwOBWheLXaBXJ+OcXe+n3J3A=
  file: dist.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    all_branched: true
    repo: VirtualJudge/VirtualJudgeFE
